(() => {
  let currentTheme = "light";
  const THEME_KEY = "site-theme";
  function getBrowserInfo() {
    const ua = navigator.userAgent;
    let browser = "Unknown";
    let version = "Unknown";

    if (ua.includes("Firefox")) {
      browser = "Firefox";
      version = ua.match(/Firefox\/(\d+)/)?.[1] || "Unknown";
    } else if (ua.includes("Edg/")) {
      browser = "Edge";
      version = ua.match(/Edg\/(\d+)/)?.[1] || "Unknown";
    } else if (ua.includes("Chrome")) {
      browser = "Chrome";
      version = ua.match(/Chrome\/(\d+)/)?.[1] || "Unknown";
    } else if (ua.includes("Safari") && !ua.includes("Chrome")) {
      browser = "Safari";
      version = ua.match(/Version\/(\d+)/)?.[1] || "Unknown";
    } else if (ua.includes("MSIE") || ua.includes("Trident/")) {
      browser = "Internet Explorer";
      version = ua.match(/(?:MSIE |rv:)(\d+)/)?.[1] || "Unknown";
    }

    return {
      browser,
      version,
      ua,
      platform: navigator.platform,
      language: navigator.language,
      cookies: navigator.cookieEnabled,
      dnt: navigator.doNotTrack,
    };
  }

  function getDisplayInfo() {
    return {
      resolution: `${screen.width} × ${screen.height}`,
      available: `${screen.availWidth} × ${screen.availHeight}`,
      colorDepth: `${screen.colorDepth}-bit`,
      pixelRatio: window.devicePixelRatio || 1,
      window: `${window.outerWidth} × ${window.outerHeight}`,
      viewport: `${window.innerWidth} × ${window.innerHeight}`,
    };
  }

  function getSystemInfo() {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    const offset = new Date().getTimezoneOffset();
    const dateFormat = new Date().toLocaleDateString();
    const cores = navigator.hardwareConcurrency || "Unknown";
    const memory = navigator.deviceMemory
      ? `${navigator.deviceMemory} GB`
      : "Unknown";
    const online = navigator.onLine ? "Online" : "Offline";

    return { tz, offset, date: dateFormat, cores, memory, online };
  }

  function getFeatureSupport() {
    return {
      javascript: "Enabled",
      localStorage: checkStorage("localStorage"),
      sessionStorage: checkStorage("sessionStorage"),
      workers: typeof Worker !== "undefined",
      serviceWorkers: "serviceWorker" in navigator,
      websockets: typeof WebSocket !== "undefined",
    };
  }

  function checkStorage(type) {
    try {
      const storage = window[type];
      const testKey = "__test__";
      storage.setItem(testKey, testKey);
      storage.removeItem(testKey);
      return true;
    } catch (e) {
      return false;
    }
  }

  function formatInfoForCopy() {
    const browser = getBrowserInfo();
    const display = getDisplayInfo();
    const system = getSystemInfo();
    const features = getFeatureSupport();

    return `=== Browser ===
User Agent: ${browser.ua}
Browser: ${browser.browser}
Version: ${browser.version}
Platform: ${browser.platform}
Language: ${browser.language}
Cookies Enabled: ${browser.cookies}
Do Not Track: ${browser.dnt}

=== Display ===
Screen Resolution: ${display.resolution}
Available: ${display.available}
Color Depth: ${display.colorDepth}
Pixel Ratio: ${display.pixelRatio}
Window Size: ${display.window}
Viewport: ${display.viewport}

=== System ===
Timezone: ${system.tz}
Offset: UTC${system.offset > 0 ? "-" : "+"}${Math.abs(system.offset / 60)}:${String(Math.abs(system.offset % 60)).padStart(2, "0")}
Date Format: ${system.date}
CPU Cores: ${system.cores}
Memory: ${system.memory}
Online: ${system.online}

=== Features ===
JavaScript: ${features.javascript}
Local Storage: ${features.localStorage}
Session Storage: ${features.sessionStorage}
Web Workers: ${features.workers}
Service Workers: ${features.serviceWorkers}
WebSockets: ${features.websockets}

---
Generated by tools.gavin.cloud/support-info`;
  }

  function displayInfo() {
    const browser = getBrowserInfo();
    document.getElementById("browser-user-agent").textContent = browser.ua;
    document.getElementById("browser-name").textContent = browser.browser;
    document.getElementById("browser-version").textContent = browser.version;
    document.getElementById("browser-platform").textContent = browser.platform;
    document.getElementById("browser-language").textContent = browser.language;
    document.getElementById("browser-cookies").textContent = browser.cookies
      ? "Yes"
      : "No";
    document.getElementById("browser-dnt").textContent =
      browser.dnt || "Not set";

    const display = getDisplayInfo();
    document.getElementById("display-resolution").textContent =
      display.resolution;
    document.getElementById("display-available").textContent =
      display.available;
    document.getElementById("display-color-depth").textContent =
      display.colorDepth;
    document.getElementById("display-pixel-ratio").textContent =
      display.pixelRatio + "x";
    document.getElementById("display-window").textContent = display.window;
    document.getElementById("display-viewport").textContent = display.viewport;

    const system = getSystemInfo();
    document.getElementById("system-timezone").textContent = system.tz;
    const offsetHours = Math.abs(system.offset / 60);
    const offsetMin = Math.abs(system.offset % 60);
    document.getElementById("system-offset").textContent =
      `UTC${system.offset > 0 ? "-" : "+"}${offsetHours}:${String(offsetMin).padStart(2, "0")}`;
    document.getElementById("system-date").textContent = system.date;
    document.getElementById("system-cores").textContent = system.cores;
    document.getElementById("system-memory").textContent = system.memory;
    document.getElementById("system-online").textContent = system.online;

    const features = getFeatureSupport();
    document.getElementById("feature-javascript").textContent =
      features.javascript;
    document.getElementById("feature-local-storage").textContent =
      features.localStorage ? "Yes" : "No";
    document.getElementById("feature-session-storage").textContent =
      features.sessionStorage ? "Yes" : "No";
    document.getElementById("feature-workers").textContent = features.workers
      ? "Yes"
      : "No";
    document.getElementById("feature-service-workers").textContent =
      features.serviceWorkers ? "Yes" : "No";
    document.getElementById("feature-websockets").textContent =
      features.websockets ? "Yes" : "No";
  }

  async function copyInfo() {
    try {
      await navigator.clipboard.writeText(formatInfoForCopy());
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  }

  function setTheme(theme) {
    currentTheme = theme;
    document.documentElement.dataset.bsTheme = theme;
    localStorage.setItem(THEME_KEY, JSON.stringify({ theme }));
  }

  const themeData = localStorage.getItem(THEME_KEY);
  if (themeData) {
    try {
      const data = JSON.parse(themeData);
      if (data.theme) currentTheme = data.theme;
    } catch (e) {
      console.warn("Failed to load theme:", e);
    }
  }
  setTheme(currentTheme);

  function init() {
    displayInfo();

    document
      .getElementById("refresh-btn")
      .addEventListener("click", displayInfo);
    document.getElementById("copy-btn").addEventListener("click", copyInfo);
  }

  document.addEventListener("DOMContentLoaded", init);

  document.getElementById("theme-toggle").addEventListener("click", () => {
    const newTheme = currentTheme === "light" ? "dark" : "light";
    setTheme(newTheme);
  });
})();
